version: '3'
services:
  app:
    container_name: scade_server
    build: .
    ports:
      - 8000:8009
    restart: on-failure
    networks:
      - fullstack

networks:
  fullstack:
    driver: bridge