version: '3'
services:
  app:
    env_file:
      - .env
    container_name: ${APP_CONTAINER}
    build: .
    ports:
      - ${APP_PORT}:8080
    depends_on:
      - mysql_db
    restart: on-failure
    networks:
      - scade_backend_server

  mysql_db:
    image: mysql:latest
    env_file:
      - .env
    container_name: ${MYSQL_DB_HOST}
    ports:
      - ${MYSQL_DB_PORT}:3306
    environment:
      - MYSQL_ROOT_HOST=${MYSQL_DB_HOST}
      - MYSQL_USER=${MYSQL_DB_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_DB_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_DB_PASSWORD}
    restart: on-failure
    networks:
      - scade_backend_server

networks:
  scade_backend_server:
    driver: bridge