version: '3'
services:
  app:
    container_name: scade_server
    build: .
    ports:
      - 8000:8009
    restart: on-failure
    depends_on:
      - mysql_db
    networks:
      - backend_connection

  mysql_db:
    image: mysql:8
    env_file:
      - .env
    container_name: ${DB_HOST}
    ports:
      - "${DB_PORT}:3306"
    environment:
      - MYSQL_ROOT_HOST=${DB_HOST}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    restart: on-failure
    networks:
      - backend_connection

networks:
  backend_connection:
    driver: bridge